### PR TITLE
Avoid injecting script to unrelated sites

### LINKED ISSUE #652: Users are getting logged out at Feedly.com
Hello, this is Petr from Feedly. Our customers since Monday keep reporting that they're being logged out and that they see this error:

Error: 929 / Bug / Authenticated requests with no session

Can you please look into this? If you need further info from Feedly devs, let me know.

### LINKED ISSUE #656: Interfering with Feedly.com "Error 929"
Browsing Feedly RSS feeds gets interrupted with an "Error 929: Authenticated request with no session" error after reading 10-15 articles.   Toggling off bypass paywall restores normal functioning.    Other users reported same issue this week via Twitter.  Incognito Mode also restores normal functioning. 

Chrome-based browsers only?   Haven't had the issue when using bp with Firefox.

### PR DESCRIPTION
**Pull request by kimkha**
Resolves #652, resolves #656

### CODE REVIEW

File: src/js/background.js [hunk 1]
```diff
@@ -347,13 +347,19 @@ extensionApi.webRequest.onBeforeSendHeaders.addListener(function (details) {
...
-    // run contentScript inside tab
-    extensionApi.tabs.executeScript(tabId, {
-      file: 'src/js/contentScript.js',
-      runAt: 'document_start'
-    }, function (res) {
-      if (extensionApi.runtime.lastError || res[0]) {
-
+    extensionApi.tabs.get(tabId, function (currentTab) {
+      // Validate url of current tab to avoid injecting script to unrelated sites
+      // See https://github.com/iamadamdev/bypass-paywalls-chrome/issues/652
```
Comment (iamadamdev) [inline src/js/background.js:352]: Can remove this

**Comment by kimkha** [comment]
Yes, it's essential step to solve the issues I mentioned [here](https://github.com/iamadamdev/bypass-paywalls-chrome/issues/652#issuecomment-633153341).

Line 267 only check enabled site against the resource URL, not the tab URL. So, if feedly.com loads an image from ft.com, there is a time that line 266 becomes `isSiteEnabled({ url: 'ft.com/an_image.jpg' })`, which returns `true`, and the content script will be loaded into that feedly.com tab.

**Comment by iamadamdev** [comment]
Good catch, thanks.
